//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int requestID { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
        public string typeOfRequest { get; set; }
        public string technicType { get; set; }
        public string technicModel { get; set; }
        public string problemDescription { get; set; }
        public string C_status { get; set; }
        public Nullable<int> sparePartID { get; set; }
        public int customerID { get; set; }
        public int masterID { get; set; }
        public int managerID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual Masters Masters { get; set; }
        public virtual RepairParts RepairParts { get; set; }
    }
}
