//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_BusinessLogic.Model
{
    using Data_BusinessLogic.DB.Interface;
    using Data_BusinessLogic.Model.DB.Interface;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    public partial class Requests : IRequests
    {
        [Key]
        public int requestID { get; set; }

        [Required]
        [JsonPropertyName("startDate")]
        public System.DateTime startDate { get; set; }

        [JsonPropertyName("completionDate")]
        public Nullable<System.DateTime> completionDate { get; set; }

        [Required]
        [MaxLength(100)]
        [JsonPropertyName("typeOfRequest")]
        public string typeOfRequest { get; set; }

        [MaxLength(100)]
        [JsonPropertyName("technicType")]
        public string technicType { get; set; }

        [MaxLength(100)]
        [JsonPropertyName("technicModel")]
        public string technicModel { get; set; }

        [MaxLength(500)]
        [JsonPropertyName("problemDescription")]
        public string problemDescription { get; set; }

        [MaxLength(50)]
        [JsonPropertyName("status")]
        public string C_status { get; set; }

        public Nullable<int> sparePartID { get; set; }

        [Required]
        public int customerID { get; set; }

        [Required]
        public int masterID { get; set; }

        [Required]
        public int managerID { get; set; }

        public virtual Customers Customers { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual Masters Masters { get; set; }
        public virtual RepairParts RepairParts { get; set; }
    }
}