//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_BusinessLogic
{
    using Data_BusinessLogic.DB.Interface;
    using Data_BusinessLogic.Model.DB.Interface;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    public partial class Users : IUsers, INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Customers = new HashSet<Customers>();
            this.Managers = new HashSet<Managers>();
            this.Masters = new HashSet<Masters>();
        }

        public event PropertyChangedEventHandler PropertyChanged;

        public int UserID { get; private set; }

        private string fio;
        [Required]
        [MaxLength(200)]
        public string Fio
        {
            get => fio;
            set
            {
                fio = value;
                OnPropertyChanged(nameof(Fio));
            }
        }

        private string phone;
        [Required]
        [MaxLength(20)]
        public string Phone
        {
            get => phone;
            set
            {
                phone = value;
                OnPropertyChanged(nameof(Phone));
            }
        }

        private string cLogin;
        [Required]
        [MaxLength(50)]
        public string C_Login
        {
            get => cLogin;
            set
            {
                cLogin = value;
                OnPropertyChanged(nameof(C_Login));
            }
        }

        private string cPassword;
        [Required]
        [MaxLength(50)]
        public string C_Password
        {
            get => cPassword;
            set
            {
                cPassword = value;
                OnPropertyChanged(nameof(C_Password));
            }
        }

        private int cType;
        [Required]
        public int C_Type
        {
            get => cType;
            set
            {
                cType = value;
                OnPropertyChanged(nameof(C_Type));
            }
        }

        protected void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Managers> Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Masters> Masters { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
