//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_BusinessLogic.Model
{
    using Data_BusinessLogic.DB.Interface;
    using Data_BusinessLogic.Model.DB.Interface;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    public partial class Users : IUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Customers = new HashSet<Customers>();
            this.Managers = new HashSet<Managers>();
            this.Masters = new HashSet<Masters>();
        }

        [Key]
        [JsonPropertyName("userId")]
        public int userID { get; set; }

        [Required]
        [MaxLength(100)]
        [JsonPropertyName("fio")]
        public string fio { get; set; }

        [Required]
        [MaxLength(20)]
        [JsonPropertyName("phone")]
        public string phone { get; set; }

        [Required]
        [MaxLength(50)]
        [JsonPropertyName("login")]
        public string C_login { get; set; }

        [Required]
        [MaxLength(50)]
        [JsonPropertyName("password")]
        public string C_password { get; set; }

        [Required]
        [JsonPropertyName("type")]
        public int C_type { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Managers> Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Masters> Masters { get; set; }
        public virtual Roles Roles { get; set; }
    }
}